# Makefile for programming challenge 17
#
# CSCI 21, Fall 2015
#
# Programmer: Ian Larkin
#



FLAGS = -Wall -Wextra -pedantic

# Target for programming challenge 17
# Date completed: 10/22/15
pc17: pc17.cpp SLNode.cpp
	g++ $(FLAGS) -o pc17 SLNode.cpp pc17.cpp
